version: '3.8'
services:
  stats-server:
    build: stats
    image: explore-with-me-stats
    container_name: explore-with-me-stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorewithme
      - SPRING_DATASOURCE_USERNAME=explorewithme
      - SPRING_DATASOURCE_PASSWORD=explorewithme

  stats-db:
    image: postgres:13.7-alpine
    container_name: explore-with-me-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=explorewithme
      - POSTGRES_USER=explorewithme
      - POSTGRES_DB=explorewithme

  ewm-server:
    build: main-ewm
    image: explore-with-me-main
    container_name: explore-with-me-main
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - stats-db
      - ewm-db
    environment:
      - explore-with-me-main.url=http://localhost:9090

  ewm-db:
    image: postgres:13.7-alpine
    container_name: explore-with-me-ewm-db
    ports:
      - "6542:5431"
    environment:
      - POSTGRES_PASSWORD=explorewithme
      - POSTGRES_USER=explorewithme
      - POSTGRES_DB=explorewithmemain